# Generated by Django 4.1.1 on 2022-11-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateTimeField(auto_now_add=True)),
                ('headline', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(null=True)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
