# Generated by Django 4.1.1 on 2022-11-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_rename_post_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='_date',
            new_name='date',
        ),
    ]
